branches:
  only:
  - src

language:
  - python

python:
  - '2.7'

install:
  - pip install -r requirements.txt

env:
  global:
    - secure: FNNRlCNkYwFJ+4/XrDF7vZSNu8VG/2Ica56NQXgIJxCxZ+7qO8sfmGxNE3iBLxvx7VoVLs86oltFlSev2o9SF/M/ns2Gn6HX8M626f/MhTNNRmwTNz7hiV+QvNWF/6BBYPG9fMnqoC1JnOO0mmsmDWnaEma/g0VNBP6x4vePUSI=
    - git submodule update --init --recursive

script:
  - pelican -s publishconf.py

notifications:
  email:
    on_success: always
    on_failure: always

after_success:
  - bash deploy.sh
