branches:
    only:
        - src

language: python

python: '2.7'

env:
  global:
    secure: FNNRlCNkYwFJ+4/XrDF7vZSNu8VG/2Ica56NQXgIJxCxZ+7qO8sfmGxNE3iBLxvx7VoVLs86oltFlSev2o9SF/M/ns2Gn6HX8M626f/MhTNNRmwTNz7hiV+QvNWF/6BBYPG9fMnqoC1JnOO0mmsmDWnaEma/g0VNBP6x4vePUSI=

install:
    - pip install -r requirements.txt

script:
    - pelican -s publishconf.py

after_success:
    - bash emptyrepo.sh
