# Site settings
title: Emmanouil Konstantinidis
description: > # Site Description
  Emmanouil Konstantinidis. Software Engineer working
  at The Times & The Sunday Times, News UK. Hobbies include JavaScript, Python, Swift and things other than programming.
keywords: emmanouil,konstantinidis,manos.im,iamemmanouil,ekonstantinidis,software engineer,dabapps,simpplr,the times,the sunday times,news uk,london,uk
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://manos.im" # the base hostname & protocol for your site

# Post settings
permalink: /blog/:title/
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
exclude:
  [
    "node_modules",
    "src",
    "package.json",
    "yarn.lock",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "webpack.config.js",
  ]

# Disqus Comments
disqusid: iamemmanouil

plugins:
  - jekyll-sitemap
