# Site settings
title: I am Emmanouil
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.iamemmanouil.com" # the base hostname & protocol for your site
twitter_username: iamemmanouil
github_username:  ekonstantinidis

# Post settings
permalink: /blog/:title
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
exclude: ['node_modules', 'Gruntfile.js', 'package.json']
