# Site settings
title: Emmanouil Konstantinidis
description: > # Site Description
  Emmanouil Konstantinidis. Web & Mobile Developer working
  at DabApps. Hobbies include JavaScript, Python, Swift and things other than programming.
keywords: emmanouil,konstantinidis,manos.im,iamemmanouil,ekonstantinidis,software engineer,dabapps,brighton,uk
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://manos.im" # the base hostname & protocol for your site

# Post settings
permalink: /blog/:title/
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
exclude: ['node_modules', 'static/scss', 'package.json', 'yarn.lock', 'Gemfile', 'Gemfile.lock', 'README.md']

# Disqus Comments
disqusid: iamemmanouil

plugins:
  - jekyll-sitemap
